controller:
  additionalPlugins:
    - kubernetes:4270.v55c41f2e3879
    - workflow-aggregator:590.v6a_d052e5a_a_b_5
    - git:5.3.0
    - pipeline-stage-view:2.33
    - credentials-binding:642.v737c34b_9ca_90
    - configuration-as-code:1837.vac9c9ff10a_14
  JCasC:
    configScripts:
      k8s-agents: |
        jenkins:
          clouds:
            - kubernetes:
                containerCapStr: "10"
                templates:
                  - name: "kaniko"
                    label: "kaniko"
                    serviceAccount: "default"
                    containers:
                      - name: "kaniko"
                        image: "gcr.io/kaniko-project/executor:latest"
                        command: ["cat"]
                        ttyEnabled: true
                      - name: "git"
                        image: "alpine/git:latest"
                        command: ["cat"]
                        ttyEnabled: true
